# Generated by Django 5.1 on 2024-11-05 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Microservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('status', models.CharField(max_length=20)),
                ('last_checked', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ErrorRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('microservice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.microservice')),
            ],
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('deployed_at', models.DateTimeField(auto_now_add=True)),
                ('microservice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.microservice')),
            ],
        ),
    ]
